language: php

php:
  - 7.2.0

before_install:
  - composer self-update

install:
  - travis_retry composer install
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - mkdir -p build/logs

script:
  - composer test

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'