language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.2
  - 7.3

before_install:
  - composer self-update

install:
  - travis_retry composer install

script:
  - composer test